server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    orders:
      path: /order/**
      serviceId: order-management-service
      strip-prefix: false
    tariffs:
      path: /tariffs/**
      serviceId: tariff-management-service
      strip-prefix: false